#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 29 19:32:47 2020

@author: fxc
"""
import random

def creationDeck():
    deck = list()
    for _ in range(4):
        deck +=  range(2, 12)
        deck += [10,10,10]
        
    random.shuffle(deck)
    return deck

deck = creationDeck()


hard_total = 0
nb_As = 0
resultats = list()

i = 0
while i < len(deck) :
    #print('Avant de commencer i = ', i)
    #print('Avant de commencer total = ', hard_total)
    
    hard_total += deck[i]
    #print('Total = ', hard_total)
    
    if deck[i] == 11 :
        nb_As += 1
        #print('nb_as = ', nb_As)
        
    if hard_total > 21 and nb_As == 0:
        #print('Cas 1 : i = ', i)
        hard_total -= deck[i]
        #print('Cas 1 : total = ', hard_total)
        resultats.append(hard_total)
        hard_total = 0
    elif hard_total > 21 and nb_As > 0:
        i+=1
        #print('Cas 2 : i = ', i)
        nb_As -= 1
        #print('Cas 2 nb_As = ', nb_As)
        hard_total -= 10
        #print('Cas 2 : total = ', hard_total)
    elif hard_total <= 21 :
        i+=1
        #print('Cas 3 i = ', i)
        
    #print('\n')

resultats.append(hard_total)
